# 운영 환경 전용 설정
services:
  mariadb:
    # ports: [] # 포트 노출 안 함 (기본값)
    volumes:
      - db_data:/var/lib/mysql # 명명된 볼륨 사용

  redis:
    # ports: []
    volumes:
      - redis_data:/data # 명명된 볼륨 사용

  backend:
    image: suho1/upbid-backend:${TAG:-latest}
    restart: unless-stopped
    # ports: []
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/${DB_DATABASE}
      SPRING_DATA_REDIS_HOST: redis
      CORS_ALLOWED_ORIGIN: ${CORS_ALLOWED_ORIGIN}
      APP_OAUTH2_REDIRECT_URI: ${APP_OAUTH2_REDIRECT_URI}
    volumes:
      - /home/ubuntu/data/uploads:/app/uploads

  frontend:
    image: suho1/upbid-frontend:${TAG:-latest}
    restart: unless-stopped
#    ports:
#      - "80:80"
#      - "443:443"
    environment: # environment 섹션 추가
      DOMAIN_NAME: ${DOMAIN_NAME}