services:
  mariadb:
    image: mariadb:10.5
    container_name: live-auction-db
    restart: always
    environment:
      TZ: Asia/Seoul
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}

  redis:
    image: redis:6.2-alpine
    container_name: live-auction-redis
    restart: always
    environment:
      TZ: Asia/Seoul

  backend:
    build: ./backend
    container_name: live-auction-backend
    restart: always
    depends_on:
      - mariadb
      - redis
    environment:
      TZ: Asia/Seoul
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      TOSS_SECRET_KEY: ${TOSS_SECRET_KEY}

  frontend:
    build: ./frontend
    container_name: live-auction-frontend
    restart: always
    depends_on:
      - backend
    environment:
      TZ: Asia/Seoul

volumes:
  db_data:
  redis_data: