services:
  mariadb:
    image: mariadb:10.5
    container_name: live-auction-db
    restart: always
    environment:
      TZ: Asia/Seoul
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}

  redis:
    image: redis:6.2-alpine
    container_name: live-auction-redis
    restart: always
    environment:
      TZ: Asia/Seoul

  backend:
    build: ./backend
    container_name: live-auction-backend
    restart: always
    depends_on:
      - mariadb
      - redis
    environment:
      TZ: Asia/Seoul
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      TOSS_SECRET_KEY: ${TOSS_SECRET_KEY}

  frontend:
    build: ./frontend
    container_name: live-auction-frontend
    restart: always
    depends_on:
      - backend
    environment:
      TZ: Asia/Seoul
    volumes:
      # Nginx와 Certbot이 공유할 볼륨들
      - certbot_conf:/etc/letsencrypt # 인증서 파일 공유
      - certbot_www:/var/www/certbot   # 도메인 소유권 확인 파일 공유


  # Certbot 서비스 신규 추가
  certbot:
    image: certbot/certbot
    container_name: live-auction-certbot
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    # 인증서 발급/갱신을 위한 명령어
    # --email: 복구용 이메일
    # --domain: 인증서를 발급받을 도메인
    command: renew --webroot -w /var/www/certbot --quiet && sleep 12h

# 명명된 볼륨 선언 (db, redis, certbot 용)
volumes:
  db_data:
  redis_data:
  certbot_conf:
  certbot_www: