spring:
  jpa:
    hibernate:
      ddl-auto: create-drop # 개발 초기에는 update 또는 create, 운영에서는 none
    show-sql: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    # docker-compose.yml의 DB_DATABASE와 동일한 값을 참조
    url: "jdbc:mariadb://localhost:3306/${DB_DATABASE}"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"

  # data 블록 아래에 redis 설정을 위치시킴
  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${GOOGLE_CLIENT_ID}"
            client-secret: "${GOOGLE_CLIENT_SECRET}"
            scope:
              - profile
              - email

# JWT 설정
jwt:
  secret: "${JWT_SECRET_KEY}"
  access-token-validity-in-seconds: 1800
  refresh-token-validity-in-seconds: 604800

# 파일 업로드 설정
file:
  upload-dir: ./uploads/ # 프로젝트 루트 아래에 uploads 폴더를 생성하여 저장