spring:
  jpa:
    hibernate:
      ddl-auto: update # 개발 초기에는 update 또는 create, 운영에서는 none
    show-sql: true
    properties:
      default_batch_fetch_size: 100
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.use_sql_comments: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    # docker-compose.yml의 DB_DATABASE와 동일한 값을 참조
    url: "jdbc:mariadb://localhost:3306/${DB_DATABASE}"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"

  # data 블록 아래에 redis 설정을 위치시킴
  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${GOOGLE_CLIENT_ID}"
            client-secret: "${GOOGLE_CLIENT_SECRET}"
            scope:
              - profile
              - email

  cache:
    type: redis # 기본 캐시 타입을 redis로 지정
    redis:
      time-to-live: 600000 # 캐시 만료 시간 (10분, 단위: 밀리초)
      cache-null-values: false # null 값은 캐싱하지 않음

  servlet:
    multipart:
      max-file-size: 10MB  # 개별 파일 최대 크기
      max-request-size: 100MB # 전체 요청 최대 크기 (여러 파일 동시 업로드 대비)

# JWT 설정
jwt:
  secret: "${JWT_SECRET_KEY}"
  access-token-validity-in-seconds: 1800
  refresh-token-validity-in-seconds: 604800

# 파일 업로드 설정
file:
  upload-dir: ./uploads/ # 프로젝트 루트 아래에 uploads 폴더를 생성하여 저장