# ===================================================================
# 로컬(local) 프로필 전용 설정
# ===================================================================
spring:
  # 로컬 DB 설정
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://localhost:3306/${DB_DATABASE}"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"
  # 로컬 Redis 설정
  data:
    redis:
      host: localhost
      port: 6379
  # JPA: 로컬에서는 앱 실행 시 테이블을 자동으로 생성 (데이터는 유지)
  jpa:
    hibernate:
      ddl-auto: update # create-drop 대신 update 사용 권장

# 프론트엔드 URL 로컬 설정
cors:
  allowed-origin: "http://localhost:3000"
app:
  oauth2:
    redirect-uri: "/auth/callback"