# ===================================================================
# 공통 Application Properties
# - 이 파일에는 local, prod 등 특정 환경에 종속되지 않는 설정만 남깁니다.
# ===================================================================
spring:
  # JPA 공통 설정
  jpa:
    show-sql: true
    properties:
      default_batch_fetch_size: 100
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
  # Security 공통 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${GOOGLE_CLIENT_ID}"
            client-secret: "${GOOGLE_CLIENT_SECRET}"
            scope:
              - profile
              - email
  # Cache 공통 설정
  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false
  # Servlet 공통 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

# 외부 서비스 공통 설정
jwt:
  secret: "${JWT_SECRET_KEY}"
  access-token-validity-in-seconds: 1800
  refresh-token-validity-in-seconds: 604800

file:
  upload-dir: ./uploads/

payment:
  toss:
    secret-key: "${TOSS_SECRET_KEY}"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  paths-to-match:
    - /api/v1/**

# --- Logging Configuration (공통) ---
# 기본 로깅 레벨은 INFO로 설정하고, 디버깅이 필요한 패키지만 DEBUG로 지정합니다.
logging:
  level:
    root: INFO
    com.suho149.liveauction: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE