name: CI/CD with Docker Hub

on:
  push:
    branches: [ main ]

env:
  DOCKER_HUB_ID: ${{ secrets.DOCKERHUB_USERNAME }}
  BACKEND_IMAGE_NAME: upbid-backend
  FRONTEND_IMAGE_NAME: upbid-frontend

jobs:
  # -------------------- 1. 빌드 및 이미지 푸시 잡 --------------------
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Generate image tag
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ env.DOCKER_HUB_ID }}/${{ env.BACKEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }}, ${{ env.DOCKER_HUB_ID }}/${{ env.BACKEND_IMAGE_NAME }}:latest
        timeout-minutes: 15 # 빌드 잡 전체의 타임아웃을 15분으로 설정

      - name: Build and push Frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ env.DOCKER_HUB_ID }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }}, ${{ env.DOCKER_HUB_ID }}/${{ env.FRONTEND_IMAGE_NAME }}:latest
#          no-cache: true
        timeout-minutes: 15

  # -------------------- 2. OCI 서버에 배포 잡 --------------------
  deploy:
    needs: build-and-push # build-and-push 잡이 성공해야만 실행
    runs-on: ubuntu-latest
    steps:
      - name: Generate image tag
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Deploy to OCI Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USERNAME }}
          key: ${{ secrets.OCI_SSH_KEY }}

          # 명령어 실행 시간을 최대 10분(600초)까지 기다려줍니다.
          command_timeout: 10m

          script: |
            # 1. 프로젝트 디렉토리로 이동
            cd /home/ubuntu/liveauction-project # 3단계에서 클론한 경로

            # 2. 최신 설정 파일(docker-compose.yml 등)을 가져오기 위해 git pull
            git pull origin main

            # 3. .env 파일 생성
            echo "${{ secrets.PROD_ENV_FILE }}" > .env

            # 4. 배포할 이미지 태그를 환경변수로 설정
            export TAG=${{ env.IMAGE_TAG }}
            
            # 5. 최신 이미지를 Docker Hub에서 pull
            #    --file 옵션을 사용하여 override 파일을 무시하도록 명시
            docker-compose --file docker-compose.yml --file docker-compose.prod.yml pull

            # 6. 컨테이너 재시작
            #    --file 옵션을 사용하여 override 파일을 무시하도록 명시
            docker-compose --file docker-compose.yml --file docker-compose.prod.yml up -d

            # 7. 오래된 Docker 이미지 정리
            docker image prune -f